### ISSUE TITLE
Can not set Invariant culture in Client

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-ClientFramework#10]
**Describe the bug**
I tried to set the Client to English, which is not available so I chose Invariant. But that is overriden with my local culture `de` everytime. As a work around I set `en` manually in the localization config.

**Expected behavior**
Either select `en` from available culture or at least invariant should not get overriden when set manually.

**Comment by slawor** [comment]
The default value of the InvariantCulture is depending to the local OS settings. So it is a correct behavior if your OS is set to german. The work around looks like it is working but the ResX files contains a `neutral` language with english translations which works like a fall back in your case. I changed the localization config to `xy` and get an english localized client too.

So in my opinion `en` is just missing in the available localizations. I  suggest to add `en` and copie the texts from neutral which are already english translations. What do you think about my suggestion @Toxantron @dbeuchler ?

**Comment by dbeuchler** [comment]
Your statement about the InvariantCulture is not correct. The InvarianCulture ist mapped to the english language but is not associated with any Country/Region. This is also part of the [documentation at microsoft]( https://docs.microsoft.com/en-US/dotnet/api/system.globalization.cultureinfo.invariantculture?view=netcore-3.1)

The neutral language is part of the [fallback process](https://docs.microsoft.com/en-us/dotnet/framework/resources/packaging-and-deploying-resources-in-desktop-apps?redirectedfrom=MSDN#net-framework-resource-fallback-process) - by default, the invariant culture will be used. In moryx we do not change the default behaviour and therefore the neutral language is equal to the invariant culture. 

For this ticket, I would prefer to have also the "en" entry within the combo box.

**Comment by Toxantron** [comment]
I am not really firm on this topic, but I definitely would like to see `en` in the combo box and hope there is a solution to avoid copying language content.

**Comment by slawor** [comment]
My fault. @dbeuchler is right about the InvariantCulture. The behavior of the neutral language and the fallback process works correctly but there are a code part which overwrites the InvariantCulture with the current ui culture. This is wrong and the reason of your problem @Toxantron . Furthermore the InvariantCulture is not realy a language which should be selectable at the UI by the user but used automatically for example in error cases. So i will fix the wrong code which overwrites the InvariantCulture, delete the InvariantCulture from the combobox and add en `en` entry for the user.
